print('''WELCOME TO DAV'S SITE''')
print("-------------------------------")
name = input("Enter your name:-")
print("-------------------------------")
age = int(input("Enter your age:-"))
print("-------------------------------")
phone_num = int(input("Enter phone:-"))
print("-------------------------------")
e_mail = input("Enter E mail:-")
print("-------------------------------")
print("You have successfully registered \nWELCOME")